apis:
  command1:
    method: GET
    url: https://api.example.com/command1
  command2:
    method: POST
    url: https://api.example.com/command2
  command3:
    method: GET
    url: https://jsonplaceholder.typicode.com/posts/1
  command4:
    method: POST
    url: https://jsonplaceholder.typicode.com/posts
  command5:
    method: POST
    url: https://jsonplaceholder.typicode.com/posts
